/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
#include <linux/kernel.h>
#include <sys/sysinfo.h>
#include <time.h>
#include <malloc.h>
#include <stdlib.h>

char **
date_1(argp, rqstp)
	long *argp;
	struct svc_req *rqstp;
{
	static char * result = "andrew";
	struct sysinfo *info = (struct sysinfo *)malloc(sizeof(struct sysinfo));
	char str[256];
	time_t rawtime;
	struct tm * time_info;
	struct mallinfo mem_info;
	double load_avg[3];
	/*
	 * insert server code here
	 */

	//printf("This is a test print the long is %ld\n", *argp);

	switch(*argp)
	{
		//This will be current system time
		case 0:
			time(&rawtime);
			time_info = localtime(&rawtime);
			printf("========================================\n");
			printf("The time and date are %s\n", asctime(time_info));	
			printf("========================================\n");
			break;
		//This will be CPU Usage
		case 1:
			printf("Getting CPU Usage\n");
			sysinfo(info);
			printf("========================================\n");
			printf("CPU Usage 1 Minute AVG: %lu\n", info->loads[0]);
			printf("CPU Usage 5 Minute AVG: %lu\n", info->loads[1]);
			printf("CPU Usage 15 Minute AVG: %lu\n", info->loads[2]);
			printf("========================================\n");
			//sprintf(str, "%lu", info->loads[0]);			
			//result = str;
			break;
		//This will be memory usage
		case 2:
			printf("Memory Usage Information\n");
			mem_info = mallinfo();
			printf("========================================\n");
			printf("Non memory mapped space allocated: %d\n", mem_info.arena);		
			printf("Number of free chunks: %d\n", mem_info.ordblks);
			printf("Number of free fastbin blocks: %d\n", mem_info.smblks);
			printf("Number of mmapped regions: %d\n", mem_info.hblks);
			printf("Space allocated in mmapped regions in bytes: %d\n", mem_info.hblkhd);
			printf("Maximum total allocated space in bytes: %d\n", mem_info.usmblks);
			printf("Space in freed fastbin blocks in bytes: %d\n", mem_info.fsmblks);
			printf("Total allocated space in bytes: %d\n", mem_info.uordblks);
			printf("Total free space in bytes: %d\n", mem_info.fordblks);
			printf("Top-most, releasable space in bytes: %d\n", mem_info.keepcost);
			printf("========================================\n");

			break;
		//This will be load procs per min
		case 3:
			
			printf("========================================\n");
			getloadavg(load_avg, 3); 
			printf("1 Minute Average: %lf\n", load_avg[0]);
			printf("5 Minute Average: %lf\n", load_avg[1]);
			printf("15 Minute Average: %lf\n", load_avg[2]);
			printf("========================================\n");
			break;
		default:
			result = "Invalid Argument\n";
			break;
	}
	return &result;
}
